# ĐỀ THI CUỐI KỲ
## Môn: Đại số tuyến tính tính toán
## Ngày: 17/05/2024
## Lớp/Lớp học phần: DHKHDL18A
## Thời gian: 60 phút

In [2]:
import numpy as np
from scipy.linalg import lu


**Câu 1. (2 điểm)** Công ty cây xanh đô thị thực hiện Dự án thay thế các cây già cỗi và cây không đúng chủng loại bởi các cây mới. Công ty thực hiện chương trình trong bốn tháng. Trong mỗi tháng công ty sẽ chặt bỏ 10% tổng số cây xanh trong thành phố tính tới ngày đầu tiên của tháng, đồng thời thực hiện trồng thêm một số cây xanh. Cụ thể trong tháng thứ nhất sẽ trồng thêm 100 cây, tháng thứ hai trồng thêm 102 cây, tháng thứ ba trồng thêm 104 cây, tháng cuối cùng trồng thêm 106 cây. Tại buổi tổng kết Dự án người ta cho biết, tổng số cây hiện tại trong thành phố đã tăng thêm 80 so với trước khi thực hiện Dự án. 

**a)** Gọi $x_0$ là số cây ban đầu và $x_1,x_2,x_3,x_4$ là số cây tương ứng ở cuối các tháng 1,2,3,4. Đặt $X=\begin{bmatrix}x_0&x_1&x_2&x_3&x_4\end{bmatrix}^T$. Dựa vào dữ kiện bài toán, xây dựng hệ phương trình tuyến tính bằng cách xác định ma trận $A$ và vector $b$ thoả $$AX=b.$$ 

**b)** Hỏi hiện nay thành phố có bao nhiêu cây xanh?

#### vì số cây ở tháng trước sẽ bị chặt 10% và được cộng thêm nên:  
$$ x_1 = 0.9x_0 + 100 $$
$$ x_2 = 0.9x_1 + 102 $$
$$ x_3 = 0.9x_2 + 104 $$
$$ x_4 = 0.9x_3 + 106 $$
$$ x_5 = 0.9x_0 + 80 $$


In [3]:
A = np.array([[-0.9,1,0,0,0],
             [0,-0.9,1,0,0],
             [0,0,-0.9,1,0],
             [0,0,0,-0.9,1],
             [-1,0,0,0,1]])
print('ma tran a: \n',A)
b = np.array([100,102,104,106,80])
print('ma tran b: \n',b)

ma tran a: 
 [[-0.9  1.   0.   0.   0. ]
 [ 0.  -0.9  1.   0.   0. ]
 [ 0.   0.  -0.9  1.   0. ]
 [ 0.   0.   0.  -0.9  1. ]
 [-1.   0.   0.   0.   1. ]]
ma tran b: 
 [100 102 104 106  80]


In [4]:
X = np.linalg.solve(A,b)
x0,x1,x2,x3,x4 = X
print('số cây ban đầu là: ',x0)
print('số cây hiện tại(sau 4 tháng): ',x4)

số cây ban đầu là:  800.0000000000002
số cây hiện tại(sau 4 tháng):  880.0000000000002


**Câu 2. (3 điểm)** Cho ma trận $X$ xác định như sau $$X=\begin{bmatrix}1 & 1 & 1\\ 4 &3 &-1\\3 & 5 & 3\end{bmatrix}.$$

**a) (1 điểm)** Phát biểu điều kiện để một ma trận vuông $A$ bất kỳ có thể phân rã dưới dạng sau (phân rã LU) $$PA=LU,$$
trong đó $P$ là ma trận hoán vị, $L$ và $U$ lần lượt ma trận tam giác dưới và tam giác trên.

**b) (2 điểm)** Ma trận $X$ đã cho có phân rã được dưới dạng LU không? Tại sao? Nếu được, hãy tìm ma trận hoán vị $P$ và hai ma trận tam giác dưới và trên $L, U$ thoả $PX=LU$.

Điều kiện: Ma trận 
𝐴
A không suy biến và có thể phân tích bằng phép khử Gauss có pivoting — tức là tại mỗi bước của quá trình khử Gauss, tồn tại một phần tử khác 0 trong cột đang xét từ dòng hiện tại trở xuống để chọn làm pivot. Khi đó, có thể sử dụng hoán vị các hàng (tức là ma trận 
𝑃
P) để đảm bảo tính khả thi.

In [5]:
#cau a:
X = np.array([[1,1,1],[4,3,-1],[3,5,3]])
print(X)

[[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]


In [6]:
P,L,U = lu(X)
print(P)
print(L)
print(U)
print(P@L@U)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]]
[[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]
[[ 1.  1.  1.]
 [ 4.  3. -1.]
 [ 3.  5.  3.]]


In [7]:
print(np.allclose(np.linalg.inv(P)@X,L@U))

True


**Câu 3. (1 điểm)** Cho $A$ là ma trận vuông cấp $2024$ và vector $b\in \mathbb{R}^{2024}$. Xác định điểm tối ưu $x^*\in \mathbb{R}^{2024}$ của bài toán sau 
$$\text{minimize }\|Ax-b\|_2^2+2025\|x\|^2_2.$$

**Câu 4. (4 điểm)** Hàng năm, Trung tâm công nghệ thông tin quản lý các kỳ thi kiểm tra năng lực về tin học. Các kỳ thi này sẽ xét các sinh viên miễn tham gia khoá học "Nhập môn tin học" cho các sinh viên có đủ năng lực. Kết quả kỳ thi có thể được xếp vào một trong các trạng thái sau: 

*Trạng thái 1:* đạt yêu cầu của bài kiểm tra và được miễn tham gia khoá học. 

*Trạng thái 2:* không đạt yêu cầu của bài kiểm tra trong lần thi thứ 3 và phải tham gia khoá học.

*Trạng thái 3:* không đạt yêu cầu của bài kiểm tra trong lần thi thứ 1.

*Trạng thái 4:* không đạt yêu cầu của bài kiểm tra trong lần thi thứ 2.

Chuyên gia giám sát kỳ thi tổng hợp số liệu và xây dựng ma trận xác suất chuyển đổi như sau:

$$P=\begin{bmatrix}1 & 0 & 0 & 0\\ 0 & 1 & 0 & 0\\0.8 & 0 & 0.1 & 0.1\\0.2 & 0.2 & 0.4 & 0.2\end{bmatrix}.$$
(Các phần tử trong ma trận $P$ tuân theo thứ tự hàng và cột lần lượt là Trạng thái 1, 2, 3, 4).

Hiện tại, có $200$ sinh viên không đạt yêu cầu của bài kiểm tra trong lần thi thứ 1 và $50$ sinh viên không đạt yêu cầu của bài kiểm tra trong lần thi thứ 2.

**a)** Giả sử rằng tất cả 250 sinh viên nêu trên tham gia đợt thi tiếp theo, hỏi có bao nhiêu sinh viên phải tham gia khoá học.

**b)** Một sinh viên sau kì thi đầu tiên ở *Trạng thái 3*. Hỏi sau ít nhất bao nhiêu lần thi nữa thì sinh viên này sẽ chắc chắn $90\%$ đạt yêu cầu của bài kiểm tra và được miễn tham gia khoá học.  

In [11]:
import numpy as np
from numpy.linalg import matrix_power
# Ma trận chuyển xác suất
P = np.array([
    [1.0, 0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0, 0.0],
    [0.8, 0.0, 0.1, 0.1],
    [0.2, 0.2, 0.4, 0.2]
])

# Vector trạng thái ban đầu: 200 sinh viên ở S3, 50 ở S4
x = np.array([0, 0, 200, 50])

# Tính trạng thái sau một lần thi
x_next = x @ matrix_power(P,1)
print(x_next[1])

10.0


In [10]:
# Vector trạng thái ban đầu: chỉ có 1 sinh viên ở trạng thái S3
v = np.array([0, 0, 1, 0])
x = 1
while True:
    p_n = v @ matrix_power(P,x)
    if (p_n[0] >= 0.9):
        print(f'khi thi đến lần {x} thì xác xuất không cần tham gia khóa học là 90%')
        break

    x +=1
    

khi thi đến lần 2 thì xác xuất không cần tham gia khóa học là 90%


## -------------------------------------------- Hết -----------------------------------------------

### Lưu ý: Sinh viên không được sử dụng internet. Giám thị không giải thích gì thêm.