**Câu 1** (3 điểm). Cho ma trận:

$$A=\left( \begin{matrix}
5 & 4 & 0 & 0 & 3 & 0 \\
4 & 5 & 0 & 2 & 2 & 0 \\
0 & 0 & 4 & 5 & 0 & 3 \\
0 & 0 & 5 & 4 & 0 & 4 \\
2 & 3 & 0 & 0 & 4 & 0 \\
\end{matrix} \right).$$

a) Phân tích SVD của ma trận A.

b) Giả sử 5 người dùng đánh giá 6 sản phẩm theo các mức độ từ 1 đến 5, người dùng thứ i đánh giá mức độ của sản phẩm j là $a_{ij}$, (trường hợp $a_{ij}$ = 0 là chưa đánh giá). Hãy dư đoán điểm đánh giá mà người dùng thứ nhất sẽ chấm cho sản phẩm 3 và 4.

In [33]:
import numpy as np
A = np.array([[5,4,0,0,3,0],[4,5,0,2,2,0],[0,0,4,5,0,3],[0,0,5,4,0,4],[2,3,0,0,4,0]])
print(A)

[[5 4 0 0 3 0]
 [4 5 0 2 2 0]
 [0 0 4 5 0 3]
 [0 0 5 4 0 4]
 [2 3 0 0 4 0]]


In [34]:
U,S,VT = np.linalg.svd(A,full_matrices= False)
sigma = np.diag(S)
print('U\n',U)
print('V^T\n',VT)
print('sigma\n',sigma)

U
 [[-0.55637643  0.32274211 -0.00463838  0.6613557  -0.38583666]
 [-0.5878278   0.19885243  0.58022414 -0.36571326  0.38014463]
 [-0.30266568 -0.60911493  0.11446335 -0.33197699 -0.64347642]
 [-0.31067101 -0.65677656 -0.20818578  0.37205723  0.53885079]
 [-0.3959555   0.23220421 -0.77902198 -0.42453167  0.04688341]]
V^T
 [[-0.53468995 -0.57325977 -0.24942895 -0.35479939 -0.39964387 -0.19408056]
 [ 0.28340663  0.29408933 -0.56417846 -0.52025344  0.22632341 -0.43932777]
 [ 0.29915395  0.22062664 -0.23582344  0.36401166 -0.79658159 -0.19791764]
 [ 0.60122003 -0.27601851  0.32172944 -0.54575536 -0.26921839  0.29750795]
 [-0.42559818  0.67323303  0.16268692 -0.40782434 -0.28345514  0.30411993]]
sigma
 [[11.0813833   0.          0.          0.          0.        ]
 [ 0.         10.13924303  0.          0.          0.        ]
 [ 0.          0.          2.47250855  0.          0.        ]
 [ 0.          0.          0.          1.6547388   0.        ]
 [ 0.          0.          0.          0.

In [35]:
#câu b:
k = 3
U_k = U[:,:k]
S_k = np.diag(S[:k])
VT_k = VT[:k,:]
R_A = np.dot(np.dot(U_k,S_k),VT_k)

maTranDanhGiaXapXi = np.clip(R_A,1,5)
print('dự đoán người dùng 1 đánh giá sản phẩm 3: ',maTranDanhGiaXapXi[0][2])
print('dự đoán người dùng 1 đánh giá sản phẩm 3: ',maTranDanhGiaXapXi[0][3])

dự đoán người dùng 1 đánh giá sản phẩm 3:  1.0
dự đoán người dùng 1 đánh giá sản phẩm 3:  1.0


**Câu 2** (4 điểm). Một nghiên cứu khảo sát hành vi chuyển mạng hoặc chuyển mang giữ số của người dùng di động tại Việt Nam cho thấy, trong mỗi tháng, tỷ lệ người dùng chuyển từ nhà mạng này sang nhà mạng khác như sau:

Tỷ lệ người dùng chuyển từ mạng VinaPhone chuyển sang mang MobiFone, Viettel, Vietnammobile lần lượt là 0.1, 0.05, 0.02

Tỷ lệ người dùng chuyến từ mạng MobiFone chuyển sang mạng VinaPhone, Viettel, Vietnammobile lần lượt là 0.15, 0.1, 0.02,

Tỷ lệ người dùng chuyển từ mạng Viettel chuyển sang mạng VinaPhone, MobiFone, Vietnammobile lần lượt là 0.1, 0.15, 0.03,
Tỷ lệ người dùng chuyển từ mạng Vietnammobile chuyển sang mạng VinaPhone, MobiFone, Viettel lần lượt là 0.3, 0.1, 0.15,
Ban đầu, số lượng người dùng của các nhà mạng được ghi nhận như sau:

VinaPhone: 40,000,000 người
MobiFone: 28,000,000 người
Viettel: 20,000,000 người
Vietnamobile: 4,000,000 người
) (2 điểm) Lập ma trận chuyển trạng thái 𝑃 (transition matrix) của quá trình này. Tính số lượng người dùng của từng nhà mạng sau 12 tháng. 

b) (2 điểm) Tính phân bố ổn định (stationary distribution) của quá trình chuyển mạng bằng phương pháp eigenvector. Dựa trên phân bố ổn định, tính số lượng người dùng ổn định của từng nhà mạng, biết tổng số người dùng không đổi

In [36]:
A = np.array([[1-0.1-0.05-0.02,0.1,0.05,0.02],
              [0.15,1-0.15-0.1-0.02,0.1,0.02],
              [0.1,0.15,1-0.1-0.15-0.03,0.03],
             [0.3,0.1,0.15,1-0.3-0.1-0.15]])
p = np.array([40000000,28000000,20000000,4000000])
print('số lượng người dùng của các nhà mạng thay đổi sau 12 tháng là: ')
from numpy.linalg import matrix_power
p_12 = p  @ matrix_power(A,12)
print(f'VinaPhone: {p_12[0] : .0f} người')
print(f'MobiPhone: {p_12[1] : .0f} người')
print(f'Viettel: {p_12[2] : .0f} người')
print(f'VietnamMobile: {p_12[3] : .0f} người')

số lượng người dùng của các nhà mạng thay đổi sau 12 tháng là: 
VinaPhone:  41774992 người
MobiPhone:  27465840 người
Viettel:  19194074 người
VietnamMobile:  3565094 người


**Câu 3**. (3 điểm) Hàng năm, Trung tâm công nghệ thông tin quản lý các kỳ thi kiểm tra năng lực về tin học. Các kỳ thi này sẽ xét các sinh viên miễn tham gia khoa học "Nhập môn tin học" cho các sinh viên có đủ năng lực. Kết quả kỳ thi có thể được xếp vào một trong các trang thái sau

Trạng thái 1: đạt yêu cầu của bài kiểm tra và được miễn tham gia khoá học

Trạng thái 2: không đạt yêu cầu của bài kiểm tra trong lần thi thứ 3 và phải tham gia khoa học

Trạng thái 3: không đạt yêu cầu của bài kiểm tra trong lần thi thứ 1.

Trạng thái 4 không đạt yêu cầu của bài kiểm tra trong lần thi thứ 2

Chuyên gia giám sát kỳ thi tổng hợp số liệu và xây dựng ma trận xác suất chuyển đổi như sau:

$$A=\left( \begin{matrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0.8 & 0 & 0.1 & 0.1 \\
0.2 & 0.2 & 0.4 & 0.2 \\
\end{matrix} \right).$$

(Các phần tử trong ma trận P tuân theo thứ tư hàng và cột lần lượt là Trạng thái 1, 2, 3, 4).
 Hiện tại, có 200 sinh viên không đạt yêu cầu của bài kiểm tra trong lần thi thứ 1 và 50 sinh viên không đạt yêu cầu của bài kiểm tra trong lần thi thứ 2.

a) Giả sử rằng tất cả 250 sinh viên nêu trên tham gia đợt thi tiếp theo, hỏi có bao nhiêu sinh viên phải tham gia khoá học.

b) Một sinh viên sau kì thi đầu tiên ở Trạng thái 3. Hỏi sau ít nhất bao nhiêu lần thì nữa thì sinh viên này sẽ chắc chắn 90% đạt yêu cầu của bài kiểm tra và được miễn tham gia khoá học

In [40]:
A = np.array([[1,0,0,0],[0,1,0,0],[0.8,0,0.1,0.1],[0.2,0.2,0.4,0.2]])
#vì sinh viên đều phải thi lại nên: có 200 sinh viên ở nhóm 3, 50 sinh viên ở nhóm 4:
p = np.array([0,0,200,50])
p1 = p @ matrix_power(A,1)
print('số sinh viên phải tham gia khóa học là: ',p1[1])
print(p1)

số sinh viên phải tham gia khóa học là:  10.0
[170.  10.  40.  30.]


In [43]:
#câu b:
#vì chỉ có 1 sinh viên đang ở trạng thái 3 nên:
p_b_0 = np.array([0,0,1,0])
for x in range(10):
    pn = p_b_0 @ matrix_power(A,x)
    if pn[0] >= 0.9:
        break
print(f'sau {x} lần thi nữa thì sinh viên đó sẽ chắc chắn 90% đạt yêu cầu và được miễn tham gia khóa học')

sau 2 lần thi nữa thì sinh viên đó sẽ chắc chắn 90% đạt yêu cầu và được miễn tham gia khóa học
