# BÀI THỰC HÀNH SỐ 2
## Môn: Đại số tuyến tính tính toán
## Ngày: 21/04/2025
## Lớp: DHKHDL19A (nhóm TH 1,2). Thời gian: 45 phút

Họ và tên: Trần Quốc Sang

MSSV: 23715111

**Câu 1. (4 điểm)**  Cho hàm số $f:\mathbb{R}^2\to \mathbb{R}$ được xác định bởi $$f(x_1,x_2)=\dfrac{x_1^2}{x_2}.$$

**a)** Xác định ma trận Hessian $\nabla^2f$.

**b)** Cho hai vector $a=(-2,-1), b=(-2,0,1)$ và ma trận $A$ xác định bởi $$A=\begin{bmatrix} \nabla^2f(-1/2,1)\\a \end{bmatrix}.$$
Tìm điểm tối ưu và giá trị tối ưu của bài toán sau $$\min_{x\in\mathbb{R}^2}\|Ax-b\|_2^2.$$

In [1]:
from sympy import symbols
import numpy as np
x1 , x2 = symbols('x1 x2')
def hesian(x1,x2):
    hesian = np.array([[2/x2,(-2*x1)/(x2**2)],
                         [(-2*x1)/(x2**2),(2*x1**2)/x2**3]])
    return hesian
print(hesian(x1,x2))

[[2/x2 -2*x1/x2**2]
 [-2*x1/x2**2 2*x1**2/x2**3]]


In [2]:
#câu b:
hesian_A = hesian(-1/2,1)

print(hesian_A)

[[2.  1. ]
 [1.  0.5]]


In [3]:
#suy ra: 
A = np.array([[2,1],[1,0.5],[-2,-1]])
b = np.array([-2, 0, 1])
diemToiUu , r, hang, giaTriKiDi = np.linalg.lstsq(A, b, rcond=None)
diemGiaTri = np.linalg.norm(A @ diemToiUu - b)**2
print('điểm tối ưu: ', diemToiUu)
print('điểm giá trị: ',diemGiaTri)

điểm tối ưu:  [-0.53333333 -0.26666667]
điểm giá trị:  1.0


**Câu 2. (4 điểm)** Theo kết quả nghiên cứu thị trường của hai cửa hàng AT và CT, người ta thấy rằng: Tất cả khách hàng mua hàng ở cửa hàng AT tại một tuần cụ thể thì trong tuần tiếp theo $90\%$ mua tiếp tục ở AT trong khi $10\%$ chuyển sang mua ở cửa hàng CT. Giả sử từ một số liệu tương tự cho các khách hàng mua hàng ở CT tại một tuần cụ thể thì trong tuần tiếp theo $80\%$ mua tiếp tại cửa hàng CT trong khi $20\%$ chuyển đến mua ở cửa hàng AT.

a) Tìm ma trận chuyển trạng thái của hai cửa hàng trên.

b) Xác định tỉ lệ cân bằng dừng.

c) Giả sử hôm nay ông B mua hàng ở AT, tính xác suất ông B mua hàng ở AT sau 2 tuần nữa.

d) Giả sử hôm nay ông B mua hàng ở CT, thì xác suất ông B sau $1$ tháng ($30$ ngày) nữa sẽ chuyển qua AT mua hàng là bao nhiêu?  


In [4]:
P = np.array([[0.9,0.1],[0.2,0.8]])
print('ma trận chuyển trạng thái: \n',P)

ma trận chuyển trạng thái: 
 [[0.9 0.1]
 [0.2 0.8]]


In [21]:
#b tỉ lệ cân bằng dừng:

A = np.array([[0.9-1,0.2],[0.1,0.8-1],[1,1]])
B = np.array([0,0,1])
pi, *a = np.linalg.lstsq(A,B,rcond=None)
print('tỉ lệ cân bằng dừng: \n', pi)

tỉ lệ cân bằng dừng: 
 [0.66666667 0.33333333]


In [6]:
#câu c: 
#vì mua ở AT nên:
from numpy.linalg import matrix_power
B_AT = np.array([1,0])
C = B_AT @ matrix_power(P,2)
print('xác xuất ông B mua ở AT sau 2 tuần: ', C[0])

xác xuất ông B mua ở AT sau 2 tuần:  0.8300000000000001


In [13]:
#câu d:
# vì hôm nay mua ở CT nên
from scipy.linalg import fractional_matrix_power
B_CT = np.array([0,1])
D = B_CT @ fractional_matrix_power(P,30/7)
print('xác xuất đến  AT mua  sau khi mua ở CT 30 ngày trước đó: ', D[0])


xác xuất đến  AT mua  sau khi mua ở CT 30 ngày trước đó:  0.5221083114616498


**Câu 3. (2 điểm)** Cho ma trận ảnh xám $A \in \mathbb{R}^{5 \times 5}$ (biểu diễn cường độ sáng của ảnh) như sau:


$$A = \begin{bmatrix}
22 & 20 & 18 & 24 & 28 \\
24 & 22 & 20 & 26 & 30 \\
26 & 24 & 22 & 28 & 32 \\
28 & 26 & 24 & 30 & 34 \\
30 & 28 & 26 & 32 & 36 \\
\end{bmatrix}.$$

a) Tìm các giá trị suy biến của $A$ trong phân rã SVD.
  
b) Giữ lại hai giá trị suy biến (singular values) lớn nhất để xấp xỉ lại ma trận $A$, gọi ma trận xấp xỉ là $A_2$. Hãy tìm ma trận $A_2$. So sánh ma trận ban đầu $A$ và ma trận xấp xỉ $A_2$, bằng cách tính sai số Frobenius giữa 2 ma trận.

Hướng dẫn: Công thức sai số Frobenius giữa 2 ma trận $A$ và $A_k$ là
$$\|A - A_k\|_F = \sqrt{ \sum_{i=1}^{m} \sum_{j=1}^{n} \left| a_{ij} - (a_k)_{ij} \right|^2 }.$$

In [16]:
A = np.array([[22,20,18,24,28],[24,22,20,26,30],[26,24,22,28,32],[28,26,24,30,34],[30,28,26,32,36]])
print(A)

[[22 20 18 24 28]
 [24 22 20 26 30]
 [26 24 22 28 32]
 [28 26 24 30 34]
 [30 28 26 32 36]]


In [18]:
U,S,VT = np.linalg.svd(A,full_matrices= False)
sigma = np.diag(S)
print('U: \n',U)
print('sigma: \n',sigma)
print('VT: \n',VT)
S

U: 
 [[-0.37847822 -0.67583595  0.63244646  0.00247166  0.00231535]
 [-0.41161488 -0.36134913 -0.63058047 -0.54567707  0.06785871]
 [-0.44475153 -0.04686231 -0.32039786  0.77533686  0.31015796]
 [-0.47788819  0.26762452  0.00275127  0.07647085 -0.83315343]
 [-0.51102484  0.58211134  0.3157806  -0.3086023   0.45282142]]
sigma: 
 [[1.33853262e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 1.81774054e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.32313484e-15 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.36402284e-16
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.05703293e-18]]
VT: 
 [[-0.43689957 -0.40367277 -0.37044597 -0.47012636 -0.53657996]
 [ 0.1087266   0.36653185  0.6243371  -0.14907866 -0.66468916]
 [ 0.25629164 -0.38755017 -0.13918227  0.73861855 -0.46817775]
 [ 0.04135686 -0.73639107  0.62242387 -0.14531283  0.21792317]
 [ 0.854342

array([1.33853262e+02, 1.81774054e+00, 8.32313484e-15, 1.36402284e-16,
       1.05703293e-18])

In [19]:
U_k = U[:, :2]
S_k = np.diag(S[:2])  
VT_k = VT[:2, :]

A_2 = U_k @ S_k @ VT_k
error = np.linalg.norm(A - A_2, 'fro')
print("Sai số Frobenius:", error)

Sai số Frobenius: 2.537145046425895e-14
